CREATE TABLE KJH_BOARD (
  ID NUMBER PRIMARY KEY,
  TITLE VARCHAR2(100) NOT NULL,
  PASSWD VARCHAR2(500) NOT NULL,
  SALT VARCHAR2(500) NOT NULL,
  CONTENT CLOB,
  USERID VARCHAR2(30),
  VIEWCOUNT NUMBER DEFAULT 0,
  REGDATE DATE,
  UPDATEDATE DATE,
  DELETEDATE DATE,
  IS_DELETED NUMBER DEFAULT 0 CHECK (IS_DELETED IN (0, 1))
);

COMMENT ON COLUMN KJH_BOARD.ID IS 'id';
COMMENT ON COLUMN KJH_BOARD.TITLE IS '제목';
COMMENT ON COLUMN KJH_BOARD.PASSWD IS '비밀 번호';
COMMENT ON COLUMN KJH_BOARD.SALT IS 'salt 값';
COMMENT ON COLUMN KJH_BOARD.CONTENT IS '내용';
COMMENT ON COLUMN KJH_BOARD.USERID IS '등록자 계정';
COMMENT ON COLUMN KJH_BOARD.VIEWCOUNT IS '조회 수';
COMMENT ON COLUMN KJH_BOARD.REGDATE IS '등록 날짜';
COMMENT ON COLUMN KJH_BOARD.UPDATEDATE IS '수정 날짜';
COMMENT ON COLUMN KJH_BOARD.DELETEDATE IS '삭제 예정 날짜';
COMMENT ON COLUMN KJH_BOARD.IS_DELETED IS '삭제 여부';


DROP TABLE KJH_BOARD;

DESC KJH_BOARD;

SELECT *
  FROM ALL_COL_COMMENTS
 WHERE TABLE_NAME = 'KJH_BOARD';


CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1HMS_NEWS KJH_BOARD HMS_NEWS 
NOMAXVALUE;



UPDATE KJH_BOARD 
SET VIEWCOUNT = VIEWCOUNT + 1 WHERE ID = 35;


SELECT * FROM ALL_SEQUENCES 
WHERE SEQUENCE_NAME = 'SEQ_BOARD';


DROP SEQUENCE SEQ_BOARD;

SELECT * FROM ALL_TRIGGERS 
WHERE TRIGGER_NAME = 'BOARD_TRIGGER';


SELECT * FROM USER_TRIGGERS 
WHERE TRIGGER_NAME = 'BOARD_TRIGGER';


INSERT INTO KJH_BOARD (ID, TITLE, CONTENT, USERID, UPDATEDATE, REGDATE)
VALUES (SEQ_BOARD.NEXTVAL, 'Sample Title', 'This is a sample content.', 'John Doe', SYSTIMESTAMP, SYSTIMESTAMP);

SELECT * FROM USER_TAB_PRIVS WHERE PRIVILEGE = 'TRIGGER';


DELETE FROM KJH_BOARD 
WHERE TO_CHAR(UPDATEDATE, 'YYYY-MM-DD') = '2023-11-14';



TRUNCATE TABLE KJH_BOARD;


SELECT SYSTIMESTAMP FROM DUAL;



UPDATE KJH_BOARD 
SET TITLE = 10, CONTENT = 10, WRITER = 10, REGDATE = SYSTIMESTAMP WHERE ID = 22;



SELECT * FROM KJH_Board      
ORDER BY id ASC
ALTER TABLE KJH_BOARD MODIFY TITLE VARCHAR2(200);


SELECT * FROM KJH_BOARD 
WHERE TO_CHAR(UPDATEDATE, 'YYYY-MM-DD') = '2023-11-14';



SELECT ROWNUM, ID, TITLE, CONTENT, PASSWD, SALT, USERID, VIEWCOUNT, REGDATE, UPDATEDATE, DELETEDATE, IS_DELETED 
FROM KJH_BOARD 
ORDER BY REGDATE DESC;


UPDATE KJH_BOARD 
SET IS_DELETED = 1, UPDATEDATE = SYSTIMESTAMP WHERE TO_CHAR(DELETEDATE, 'YYYY-MM-DD') = '2023-11-16';